name: Migrate to Target

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  migrate_to_target:
    name: Migration to Target
    runs-on: ubuntu-latest
    env:
      SOURCE_HOST_URL: ${{ secrets.SOURCE_HOST_URL }}
      SOURCE_TOKEN: ${{ secrets.SOURCE_TOKEN }}
      TARGET_HOST_URL: ${{ secrets.TARGET_HOST_URL }}
      TARGET_TOKEN: ${{ secrets.TARGET_TOKEN }}
      
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          VERSION=$(ls cicd_aihub-*-py3-none-any.whl | sed 's/cicd_aihub-\(.*\)-py3-none-any.whl/\1/' | head -n 1)

          if [ -n "$VERSION" ]; then
            echo "Found local .whl file: cicd_aihub-${VERSION}-py3-none-any.whl"
            pipx install cicd_aihub-${VERSION}-py3-none-any.whl
          else
            echo "No local .whl file found. Attempting to install from GitHub release."
            LATEST_RELEASE=$(curl -s https://api.github.com/repos/instabase/aihub-apps-ci-cd-workflows/releases/latest | jq -r .tag_name)
            VERSION=$(echo $LATEST_RELEASE | sed 's/^v//')
            
            if ! pipx install https://github.com/instabase/aihub-apps-ci-cd-workflows/releases/download/${LATEST_RELEASE}/cicd_aihub-${VERSION}-py3-none-any.whl; then
              echo "Failed to install from GitHub release. Aborting."
              exit 1
            fi
          fi

      - name: Validate config.json
        run: |
          if [ ! -f config.json ]; then
            echo "Error: config.json file not found"
            exit 1
          fi

          APP_ID=$(jq -r '.source.app_id' config.json)
          if [ -z "$APP_ID" ] || [ "$APP_ID" = "null" ]; then
            echo "Error: app_id is missing or null in config.json"
            exit 1
          fi

      - name: Migrate app to Target
        run: |
          IS_ADVANCED=$(jq -r '.source.is_advanced' config.json)
          SB_NAME=$(jq -r '.source.sb_name' config.json)
          FLOW_PATH=$(jq -r '.source.flow_path' config.json)
          DEPLOYMENT_ID=$(jq -r '.source.deployment_id' config.json)
          DEPENDENCIES=$(jq -r '.source.dependencies' config.json)
          REBUILD=$(jq -r '.settings.rebuild' config.json)

          DEPLOY_FLAG=$([ -n "$DEPLOYMENT_ID" ] && [ "$DEPLOYMENT_ID" != "null" ] && echo "--create_deployment")
          DEPS_FLAG=$([ -n "$DEPENDENCIES" ] && [ "$DEPENDENCIES" != "null" ] && echo "--upload_dependencies")
          REBUILD_FLAG=$([ "$REBUILD" = "true" ] && echo "--rebuild")

          if [ "$IS_ADVANCED" = "true" ] && [ -n "$FLOW_PATH" ] && [ "$FLOW_PATH" != "null" ]; then
            promote-solution --promote_solution_to_target --publish_advanced_app $DEPLOY_FLAG $DEPS_FLAG
          elif [ "$IS_ADVANCED" = "true" ] && [ -n "$SB_NAME" ] && [ "$SB_NAME" != "null" ]; then
            promote-sb-solution --promote_solution_to_target --publish_advanced_app $DEPLOY_FLAG $DEPS_FLAG
          else
            promote-build-solution --publish_build_app $DEPLOY_FLAG $REBUILD_FLAG
          fi

      - name: Configure Git Identity
        run: |
          git config user.email "no-reply@github.com"
          git config user.name "GitHub Actions"

      - name: Create Tag for Release
        if: success()
        run: |
          APP_RELEASE_VERSION=$(jq -r '.version' app_details.json)
          git tag -a "v${APP_RELEASE_VERSION}" -m "Release version ${APP_RELEASE_VERSION}"
          git push origin "v${APP_RELEASE_VERSION}"
